version: '3'

services:
  db:
    image: postgres

  web:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
