# Based on https://stackoverflow.com/questions/37089162/docker-compose-volume-mount-before-run

FROM node:7

RUN mkdir /project
RUN mkdir /assets-builder
WORKDIR /assets-builder
ADD docker_dev/assets-builder.sh /assets-builder/
RUN chmod +x ./assets-builder.sh

ENV NODE_ENV development
CMD /assets-builder/assets-builder.sh
