# Based on https://docs.docker.com/compose/django/

FROM python:3.6

RUN mkdir /project
WORKDIR /project
ADD requirements.txt /project/

ENV PYTHONUNBUFFERED 1
RUN pip install -r requirements.txt
ADD . /project/
